In [12]:
import torch

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [4]:
model_name = "gpt2"

In [5]:
sentence = "John loves Mary very much."

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [7]:
inputs = tokenizer(sentence, return_tensors="pt")

In [8]:
inputs

{'input_ids': tensor([[ 7554, 10408,  5335,   845,   881,    13]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

In [17]:
tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

In [18]:
tokens

['John', 'Ġloves', 'ĠMary', 'Ġvery', 'Ġmuch', '.']

In [26]:
model = AutoModelForCausalLM.from_pretrained(model_name, output_attentions=True)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [27]:
outputs = model(**inputs)

In [21]:
outputs

CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[ -34.1368,  -33.6299,  -36.7537,  ...,  -41.8392,  -40.9405,
           -33.8310],
         [ -75.4397,  -75.8069,  -81.5804,  ...,  -82.4031,  -83.8337,
           -77.5075],
         [ -70.5976,  -70.9662,  -79.2872,  ...,  -84.5300,  -83.4069,
           -74.7621],
         [ -75.9247,  -77.0390,  -87.8869,  ...,  -89.8265,  -88.3588,
           -82.2927],
         [ -57.8530,  -59.2989,  -66.5427,  ...,  -74.4148,  -74.1016,
           -61.3462],
         [-146.9636, -146.2070, -147.8792,  ..., -160.1386, -160.4682,
          -140.0911]]], grad_fn=<UnsafeViewBackward0>), past_key_values=((tensor([[[[-1.1972e+00,  1.9275e+00,  5.1193e-01,  ..., -7.4685e-01,
           -5.0014e-01,  1.5532e+00],
          [-1.5396e+00,  2.1734e+00,  1.9034e+00,  ..., -2.1588e+00,
           -2.2514e+00,  1.4367e+00],
          [-1.2554e+00,  2.7217e+00,  1.9530e+00,  ..., -2.8874e+00,
           -9.2783e-01,  1.9759e+00],
          [-3.439

In [28]:
As = outputs.attentions

In [29]:
As

(tensor([[[[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
            0.0000e+00],
           [9.0743e-01, 9.2567e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,
            0.0000e+00],
           [7.3173e-01, 1.3326e-01, 1.3501e-01, 0.0000e+00, 0.0000e+00,
            0.0000e+00],
           [3.4314e-01, 3.6774e-01, 1.7140e-01, 1.1772e-01, 0.0000e+00,
            0.0000e+00],
           [3.3888e-01, 2.9147e-01, 1.9151e-01, 1.0137e-01, 7.6774e-02,
            0.0000e+00],
           [4.0300e-01, 2.2326e-01, 1.1299e-01, 1.0651e-01, 1.3833e-01,
            1.5904e-02]],
 
          [[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
            0.0000e+00],
           [1.7165e-04, 9.9983e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
            0.0000e+00],
           [9.8891e-05, 8.8757e-04, 9.9901e-01, 0.0000e+00, 0.0000e+00,
            0.0000e+00],
           [9.8228e-05, 7.7412e-04, 5.7816e-04, 9.9855e-01, 0.0000e+00,
            0.0000e+00],
           [3.4600e-04, 1.0

In [30]:
len(As)

12

In [31]:
A = As[-1] # last attention layer

In [32]:
A

tensor([[[[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
           0.0000e+00],
          [4.4836e-01, 5.5164e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
           0.0000e+00],
          [8.3616e-01, 9.2094e-02, 7.1741e-02, 0.0000e+00, 0.0000e+00,
           0.0000e+00],
          [5.8067e-01, 2.8738e-01, 8.6317e-02, 4.5637e-02, 0.0000e+00,
           0.0000e+00],
          [1.5466e-01, 2.2404e-01, 1.2055e-01, 1.1205e-01, 3.8870e-01,
           0.0000e+00],
          [3.4435e-01, 7.1356e-02, 1.2561e-01, 3.0158e-02, 1.0394e-01,
           3.2458e-01]],

         [[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
           0.0000e+00],
          [9.2787e-01, 7.2126e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,
           0.0000e+00],
          [9.3315e-01, 3.4328e-02, 3.2526e-02, 0.0000e+00, 0.0000e+00,
           0.0000e+00],
          [9.1765e-01, 4.0085e-02, 3.5321e-02, 6.9444e-03, 0.0000e+00,
           0.0000e+00],
          [7.1845e-01, 7.5017e-02, 1.6731e-01, 1

In [33]:
A.shape # this model has 12 head

torch.Size([1, 12, 6, 6])

In [37]:
# get the first head
H = A[0,0].detach().numpy()

In [38]:
H

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.44835734, 0.55164266, 0.        , 0.        , 0.        ,
        0.        ],
       [0.83616483, 0.0920945 , 0.07174073, 0.        , 0.        ,
        0.        ],
       [0.5806694 , 0.28737625, 0.08631749, 0.04563684, 0.        ,
        0.        ],
       [0.15465976, 0.2240432 , 0.12055188, 0.11204851, 0.38869667,
        0.        ],
       [0.34435317, 0.07135614, 0.1256132 , 0.03015827, 0.10394394,
        0.32457525]], dtype=float32)

In [41]:
# get all 12 heads
Hs = [A[0,h].detach().numpy() for h in range(0,12)]

In [44]:
Hs

[array([[1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.44835734, 0.55164266, 0.        , 0.        , 0.        ,
         0.        ],
        [0.83616483, 0.0920945 , 0.07174073, 0.        , 0.        ,
         0.        ],
        [0.5806694 , 0.28737625, 0.08631749, 0.04563684, 0.        ,
         0.        ],
        [0.15465976, 0.2240432 , 0.12055188, 0.11204851, 0.38869667,
         0.        ],
        [0.34435317, 0.07135614, 0.1256132 , 0.03015827, 0.10394394,
         0.32457525]], dtype=float32),
 array([[1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.92787397, 0.07212596, 0.        , 0.        , 0.        ,
         0.        ],
        [0.9331467 , 0.0343277 , 0.03252558, 0.        , 0.        ,
         0.        ],
        [0.91765034, 0.0400847 , 0.03532065, 0.00694436, 0.        ,
         0.        ],
        [0.7184488 , 0.07501739, 0.16731188, 0.01589774, 0.02332414,
    

In [46]:
# compute average across all matrices
import numpy as np

In [49]:
np.mean(Hs, axis=0)

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.80157965, 0.19842033, 0.        , 0.        , 0.        ,
        0.        ],
       [0.8379392 , 0.09588918, 0.06617162, 0.        , 0.        ,
        0.        ],
       [0.77797174, 0.12551741, 0.05528675, 0.04122409, 0.        ,
        0.        ],
       [0.6648795 , 0.10501576, 0.10455237, 0.04886515, 0.07668719,
        0.        ],
       [0.62329966, 0.05898935, 0.10478605, 0.01856679, 0.02442277,
        0.16993533]], dtype=float32)